import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"getURLSearchParams","description":"","frontmatter":{},"headers":[],"relativePath":"utils/browser/getURLSearchParams.md","filePath":"utils/browser/getURLSearchParams.md"}');
const _sfc_main = { name: "utils/browser/getURLSearchParams.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="geturlsearchparams" tabindex="-1">getURLSearchParams <a class="header-anchor" href="#geturlsearchparams" aria-label="Permalink to &quot;getURLSearchParams&quot;">​</a></h1><p>读取当前页面的查询参数：不传参返回全部，传参返回单个值。</p><h2 id="基础用法" tabindex="-1">基础用法 <a class="header-anchor" href="#基础用法" aria-label="Permalink to &quot;基础用法&quot;">​</a></h2><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">// 当前地址：https://example.com/list?page=2&amp;tab=all</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">getURLSearchParams</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">() </span><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">// { page: &#39;2&#39;, tab: &#39;all&#39; }</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">getURLSearchParams</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&#39;page&#39;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">) </span><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">// &#39;2&#39;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">getURLSearchParams</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">&#39;notExist&#39;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">) </span><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">// null</span></span></code></pre></div><h2 id="api" tabindex="-1">API <a class="header-anchor" href="#api" aria-label="Permalink to &quot;API&quot;">​</a></h2><p>函数带重载，两种用法：</p><table tabindex="0"><thead><tr><th style="${ssrRenderStyle({ "text-align": "left" })}">参数</th><th style="${ssrRenderStyle({ "text-align": "left" })}">说明</th><th style="${ssrRenderStyle({ "text-align": "left" })}">类型</th><th style="${ssrRenderStyle({ "text-align": "left" })}">默认值</th><th style="${ssrRenderStyle({ "text-align": "left" })}">是否必填</th></tr></thead><tbody><tr><td style="${ssrRenderStyle({ "text-align": "left" })}">param</td><td style="${ssrRenderStyle({ "text-align": "left" })}">参数名，不传则返回全部参数</td><td style="${ssrRenderStyle({ "text-align": "left" })}"><code>string</code></td><td style="${ssrRenderStyle({ "text-align": "left" })}">-</td><td style="${ssrRenderStyle({ "text-align": "left" })}">否</td></tr></tbody></table><table tabindex="0"><thead><tr><th style="${ssrRenderStyle({ "text-align": "left" })}">返回值</th><th style="${ssrRenderStyle({ "text-align": "left" })}"><code>Record&lt;string, string&gt;</code>（不传参）或 <code>string | null</code>（传参）</th></tr></thead></table><h2 id="注意事项" tabindex="-1">注意事项 <a class="header-anchor" href="#注意事项" aria-label="Permalink to &quot;注意事项&quot;">​</a></h2><ul><li><strong>SSR 安全</strong>：<code>typeof window === &#39;undefined&#39;</code> 时返回空对象 <code>{}</code>，不会抛错。但注意此时<strong>传了 <code>param</code> 也会返回 <code>{}</code> 而不是 <code>null</code></strong>，服务端渲染时的空值判断要按对象处理。</li><li>返回值都是<strong>字符串</strong>，<code>?page=2</code> 拿到的是 <code>&#39;2&#39;</code> 不是 <code>2</code>，比大小前记得转换。</li><li>取不到指定参数时返回 <code>null</code>（浏览器环境下），不是 <code>undefined</code>、也不是空字符串。</li><li>值<strong>会</strong>被 <code>URLSearchParams</code> 自动解码：<code>?q=a%20b</code> 得到 <code>&#39;a b&#39;</code>，这一点与 <code>parseQuery</code> 不同（后者不解码）。</li><li>同名参数出现多次时，<code>get()</code> 取到<strong>第一个</strong>值；需要全部时请自己用 <code>getAll()</code>。</li><li>读的是 <code>window.location.search</code>，只反映<strong>当前页面地址</strong>；解析任意字符串请用 <code>parseQuery</code> 或 <code>URLSearchParams</code>。</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("utils/browser/getURLSearchParams.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const getURLSearchParams = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  getURLSearchParams as default
};
