import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"getBrowserInfo","description":"","frontmatter":{},"headers":[],"relativePath":"utils/browser/getBrowserInfo.md","filePath":"utils/browser/getBrowserInfo.md"}');
const _sfc_main = { name: "utils/browser/getBrowserInfo.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="getbrowserinfo" tabindex="-1">getBrowserInfo <a class="header-anchor" href="#getbrowserinfo" aria-label="Permalink to &quot;getBrowserInfo&quot;">​</a></h1><p>解析 <code>userAgent</code>，得到浏览器名称、主版本号与是否移动端。</p><h2 id="基础用法" tabindex="-1">基础用法 <a class="header-anchor" href="#基础用法" aria-label="Permalink to &quot;基础用法&quot;">​</a></h2><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> info</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> getBrowserInfo</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">()</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">console.</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}">log</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(info)</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">// { name: &#39;Chrome&#39;, version: &#39;131&#39;, isMobile: false }</span></span></code></pre></div><p>按浏览器做差异化处理：</p><div class="language-tsx vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">tsx</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">import</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> { getBrowserInfo } </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">from</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> &#39;ono-react-element&#39;</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">function</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> App</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">() {</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">  const</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> { </span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}">name</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> } </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> getBrowserInfo</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">()</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">  return</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> &lt;</span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">div</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&gt;{name </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">===</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> &#39;Safari&#39;</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> ?</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> &#39;提示：Safari 请手动允许自动播放&#39;</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> :</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> &#39;播放中&#39;</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}&lt;/</span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">div</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">&gt;</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">}</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">export</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> default</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> App;</span></span></code></pre></div><h2 id="api" tabindex="-1">API <a class="header-anchor" href="#api" aria-label="Permalink to &quot;API&quot;">​</a></h2><table tabindex="0"><thead><tr><th style="${ssrRenderStyle({ "text-align": "left" })}">返回值</th><th style="${ssrRenderStyle({ "text-align": "left" })}"><code>BrowserInfo</code></th></tr></thead></table><h3 id="browserinfo" tabindex="-1">BrowserInfo <a class="header-anchor" href="#browserinfo" aria-label="Permalink to &quot;BrowserInfo&quot;">​</a></h3><table tabindex="0"><thead><tr><th style="${ssrRenderStyle({ "text-align": "left" })}">字段</th><th style="${ssrRenderStyle({ "text-align": "left" })}">说明</th><th style="${ssrRenderStyle({ "text-align": "left" })}">类型</th></tr></thead><tbody><tr><td style="${ssrRenderStyle({ "text-align": "left" })}">name</td><td style="${ssrRenderStyle({ "text-align": "left" })}">浏览器名称，识别不出时为 <code>&#39;Unknown&#39;</code></td><td style="${ssrRenderStyle({ "text-align": "left" })}"><code>string</code></td></tr><tr><td style="${ssrRenderStyle({ "text-align": "left" })}">version</td><td style="${ssrRenderStyle({ "text-align": "left" })}">主版本号字符串，识别不出时为 <code>&#39;Unknown&#39;</code></td><td style="${ssrRenderStyle({ "text-align": "left" })}"><code>string</code></td></tr><tr><td style="${ssrRenderStyle({ "text-align": "left" })}">isMobile</td><td style="${ssrRenderStyle({ "text-align": "left" })}">是否移动端，直接复用 <code>isMobile</code> 常量</td><td style="${ssrRenderStyle({ "text-align": "left" })}"><code>boolean</code></td></tr></tbody></table><h2 id="注意事项" tabindex="-1">注意事项 <a class="header-anchor" href="#注意事项" aria-label="Permalink to &quot;注意事项&quot;">​</a></h2><ul><li><strong>现代 Edge 识别不出来，会被报成 <code>Chrome</code></strong>。判定顺序是 Chrome → Firefox → Safari → Edge，而 Chromium 版 Edge 的 UA 里同时含有 <code>Chrome/xx</code>，会先命中 Chrome 分支；而且现在 Edge 的标识是 <code>Edg/xx</code>，源码里匹配的却是旧的 <code>Edge/(\\d+)</code>，即便顺序调对也匹配不上。</li><li>Chrome 系的一众浏览器（国内常见的内核套壳浏览器、Opera、Brave）也会统一报成 <code>Chrome</code>，它识别的是<strong>内核</strong>而不是品牌。</li><li>Safari 分支要求 UA 里同时有 <code>Safari/</code> 和 <code>Version/</code>，这是正常的 Safari 写法；但 iOS 上的 Chrome / Firefox 也是 Safari 内核，会落到 Safari 分支。</li><li>只取<strong>主版本号</strong>（<code>\\d+</code>），拿不到 <code>131.0.6778.86</code> 这样的完整版本。</li><li>依赖 <code>navigator.userAgent</code>，SSR 环境下会抛错；且 UA 可以被客户端伪造，不要拿它做安全判断。</li><li>返回值里的 <code>isMobile</code> 来自模块常量，移动端的判定规则见 <code>isMobile</code>。</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("utils/browser/getBrowserInfo.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const getBrowserInfo = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  getBrowserInfo as default
};
