import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"fileToBase64","description":"","frontmatter":{},"headers":[],"relativePath":"utils/file/fileToBase64.md","filePath":"utils/file/fileToBase64.md"}');
const _sfc_main = { name: "utils/file/fileToBase64.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="filetobase64" tabindex="-1">fileToBase64 <a class="header-anchor" href="#filetobase64" aria-label="Permalink to &quot;fileToBase64&quot;">​</a></h1><p>把 <code>File</code> 转成 base64 字符串，<strong>结果包含 data URL 前缀，可直接当图片地址使用</strong>。</p><h2 id="基础用法" tabindex="-1">基础用法 <a class="header-anchor" href="#基础用法" aria-label="Permalink to &quot;基础用法&quot;">​</a></h2><div class="language-ts vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">ts</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">const</span><span style="${ssrRenderStyle({ "--shiki-light": "#005CC5", "--shiki-dark": "#79B8FF" })}"> base64</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> =</span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}"> await</span><span style="${ssrRenderStyle({ "--shiki-light": "#6F42C1", "--shiki-dark": "#B392F0" })}"> fileToBase64</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">(file)</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">img.src </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">=</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}"> base64 </span><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}">// 直接拿来预览，不用再拼前缀</span></span></code></pre></div><h2 id="api" tabindex="-1">API <a class="header-anchor" href="#api" aria-label="Permalink to &quot;API&quot;">​</a></h2><table tabindex="0"><thead><tr><th style="${ssrRenderStyle({ "text-align": "left" })}">参数</th><th style="${ssrRenderStyle({ "text-align": "left" })}">说明</th><th style="${ssrRenderStyle({ "text-align": "left" })}">类型</th><th style="${ssrRenderStyle({ "text-align": "left" })}">默认值</th><th style="${ssrRenderStyle({ "text-align": "left" })}">是否必填</th></tr></thead><tbody><tr><td style="${ssrRenderStyle({ "text-align": "left" })}">file</td><td style="${ssrRenderStyle({ "text-align": "left" })}">待转换的 File</td><td style="${ssrRenderStyle({ "text-align": "left" })}"><code>File</code></td><td style="${ssrRenderStyle({ "text-align": "left" })}">-</td><td style="${ssrRenderStyle({ "text-align": "left" })}">是</td></tr></tbody></table><table tabindex="0"><thead><tr><th style="${ssrRenderStyle({ "text-align": "left" })}">返回值</th><th style="${ssrRenderStyle({ "text-align": "left" })}"><code>Promise&lt;string&gt;</code>（形如 <code>data:image/png;base64,xxxx</code>）</th></tr></thead></table><h2 id="注意事项" tabindex="-1">注意事项 <a class="header-anchor" href="#注意事项" aria-label="Permalink to &quot;注意事项&quot;">​</a></h2><ul><li>与 <code>blobToBase64</code> 的区别就在前缀：<strong>这个带前缀</strong>（内部直接返回 <code>reader.result</code>），那个不带。</li><li>内部走 <code>FileReader.readAsDataURL</code>，<strong>没有 <code>onerror</code> 处理</strong>，读取失败时 Promise 会一直挂着，不会 reject。</li><li>前缀里的 MIME 取自文件的 <code>type</code>；如果文件本身没有 <code>type</code>（比如手动构造的 <code>File</code>），前缀会是 <code>data:application/octet-stream</code> 之类，浏览器可能不按图片渲染。</li><li>base64 体积约为原文件的 1.37 倍，只适合小图预览；大文件请用 <code>URL.createObjectURL</code>。</li><li>反过来把带前缀的 base64 转回文件用 <code>base64ToFile</code>。</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("utils/file/fileToBase64.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const fileToBase64 = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  fileToBase64 as default
};
